sudo: required
dist: trusty
before_script:
    - sudo apt-get -q update
    - sudo apt-get install -y yasm nasm
    - ./autogen.sh
env:
    matrix:
        - CONFIGURE_FLAGS=
        - CONFIGURE_FLAGS="--host=i686-pc-linux-gnu CFLAGS=\'-m32 -g -O2\'"
script: ./configure $CONFIGURE_FLAGS && make && make check
language: c
compiler:
    - clang
    - gcc
