sudo: required
dist: trusty
os:
 - linux
 - osx
before_script:
    - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get -q update; fi
    - if [[ $TRAVIS_OS_NAME == linux ]]; then sudo apt-get install -y yasm nasm gcc-multilib; fi
    - if [[ $TRAVIS_OS_NAME = osx ]]; then brew install yasm; fi
    - ./autogen.sh
env:
    matrix:
        - CONFIGURE_FLAGS= CFLAGS="-g -O2"
        - CONFIGURE_FLAGS=--host=i686-pc-linux-gnu CFLAGS="-m32 -g -O2"
matrix:
    exclude:
        - os: osx
          env: CONFIGURE_FLAGS=--host=i686-pc-linux-gnu CFLAGS="-m32 -g -O2"


script: ./configure $CONFIGURE_FLAGS CFLAGS="$CFLAGS" && make && make check test
language: c
compiler:
    - clang
    - gcc
